
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:5000
    working_dir: /app
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    working_dir: /app 